language: python
arch:
  - amd64
  - ppc64le
python:
  - pypy
  - pypy3.5
  - 2.7
  - 3.4
  - 3.5
  - 3.6
jobs:
  exclude:
   - arch : ppc64le
     python : pypy
   - arch : ppc64le
     python : pypy3.5	
install:
  - pip install coveralls tox-travis
script: tox
after_success: coveralls
